export let products = [
    {
      id:1,
      product_name:'iPhone 15 Pro',
      product_brand:'Apple',
      product_category:'Elektronik',
      product_image : 'https://nw.ax/Mr6',
      product_price: '65.000₺',
      stock:6,
    },
    {
      id:2,
      product_name:'iPhone 15 Pro Max',
      product_brand:'Apple',
      product_category:'Elektronik',
      product_image : 'https://gx.ax/Ts5',
      product_price: '75.000 ₺',
      stock:1,
    },
    {
      id:3,
      product_name:'RTX 3070',
      product_brand:'Nvidia',
      product_category:'Elektronik',
      product_image : 'https://wx.ax/6Vo',
      product_price: '25.000₺',
      stock:2,
    },
    {
      id:4,
      product_name:'Airpods pro 2. nesil',
      product_brand:'Apple',
      product_category:'Elektronik',
      product_image : 'https://nx.ax/n0Y',
      product_price:'5.000₺',
      stock:23,
    },
    {
      id:5,
      product_name:'Limon Kolanyası',
      product_brand:'Karayel',
      product_category:'Kişisel Bakım',
      product_image : 'https://sq.ax/4Qv',
      product_price: '30₺',
      stock:50,
    },
    {
      id:6,
      product_name:'Polo Yaka Tshirt',
      product_brand:'Lacoste',
      product_category:'Giyim',
      product_image : 'https://ft.ax/o8G',
      product_price:'2500₺',
      stock:5,
    }
  ];